blank_issues_enabled: false
contact_links:
  - name: Ask Google
    url: htttp://www.google.com
    about: Have a question? Need some help from the community? Refer to the documentation because someone has probably asked it already.
